---
title: "dataprep"
author: "doh"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
    keep_md: yes
  word_document: 
    toc: yes
    fig_caption: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data


```{r cars}
library(haven)
library(data.table)
library(readxl)
```

## Including Plots



```{r pressure, echo=FALSE}
sav4 <- "/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr1-4a_personleveldietarydata_uk_v2.sav"

sav4b <- "/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr1-4a_indiv_uk.sav"

sav6 <-"/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr5-6a_personleveldietarydata_v2.sav"

sav6b <- "/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr5-6a_indiv.sav"

sav8 <-"/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr7-8a_personleveldietarydata.sav"

sav8b <- "/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr7-8a_indiv.sav"



sav11 <- "/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr9-11a_personleveldietarydata_uk_20210831.sav"

sav11b <- "/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr9-11a_indiv_20211020.sav"

sav4r <- as.data.table(read_sav(sav4))
sav4br <-as.data.table(read_sav(sav4b))

sav6r <- as.data.table(read_sav(sav6))
sav6br <-as.data.table(read_sav(sav6b))

sav8r <- as.data.table(read_sav(sav8))
sav8br <-as.data.table(read_sav(sav8b))


sav11r <- as.data.table(read_sav(sav11))
sav11br <- as.data.table(read_sav(sav11b))
```



```{r include=FALSE}
#this identifies the variables wanted from the person level data sets
#perslevdat4 <- c("seriali","Age", "Sex","Country","Sodiummg","Calciummg","VitaminDµg","TotalEMJ", "Totalsugarsg","Glucoseg","Sucroseg","Fructoseg","Lactoseg","SOFTDRINKSLOWCALORIE","SOFTDRINKSNOTLOWCALORIE", "TEACOFFEEANDWATER")

perslevdat4z <- c("seriali","Sodiummg","Calciummg","VitaminDµg","TotalEMJ")
perslevdat6z <- c("seriali","Sodiummg","Calciummg","VitaminDµg","TotalEMJ")
perslevdat8z <- c("seriali","Sodiummg","Calciummg","VitaminDµg","TotalEMJ")
perslevdat11z<- c("seriali","Sodiummg","Calciummg","VitaminDµg","TotalEMJ")
#perslevdat6 <- c("seriali","Age", "Sex","Country","Sodiummg","Calciummg","VitaminDµg","TotalEMJ", "Totalsugarsg","Glucoseg","Sucroseg","Fructoseg","Lactoseg","SOFTDRINKSLOWCALORIE","SOFTDRINKSNOTLOWCALORIE", "TEACOFFEEANDWATER")

#perslevdat8 <- c("seriali","Age", "Sex","Country","Sodiummg","Calciummg","VitaminDµg","TotalEMJ", "Totalsugarsg","Glucoseg","Sucroseg","Fructoseg","Lactoseg","SOFTDRINKSLOWCALORIE","SOFTDRINKSNOTLOWCALORIE", "TEACOFFEEANDWATER")


#perslevdat11 <- c("seriali","AgeR", "Sex","Country","Sodiummg","Calciummg","VitaminDµg","TotalEMJ", "Totalsugarsg","Glucoseg","Sucroseg","Fructoseg","Lactoseg","SOFTDRINKSLOWCALORIE","SOFTDRINKSNOTLOWCALORIE", "TEACOFFEEANDWATER")

sav4rpz <- sav4r[, ..perslevdat4z]
sav6rpz <- sav6r[, ..perslevdat6z]
sav8rpz <- sav8r[, ..perslevdat8z]
sav11rpz <- sav11r[, ..perslevdat11z]

earlyrp <- rbindlist(list(sav4rpz,sav6rpz,sav8rpz,sav11rpz))
earlyrp

NOVA_ForDavid <- as.data.table(read_excel("data/NOVA_ForDavid.xlsx"))

NOVA_ForDavid[, Sex := factor(Sex, levels = 1:2)]
NOVA_ForDavid[, Country := factor(Country)]
NOVA_ForDavid[, SurveyYear := factor(SurveyYear)]
NOVA_ForDavid[, Age := as.numeric(Age)]
```


```{r 4setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr1-4a_indiv_uk 
#subsets of the table to identify grouped information
bpset4z <- sav4br[,c("seriali","omsysval","omdiaval")]
ethnset4z <- sav4br[,c("seriali","ethgr2")]
saltset4z <- sav4br[,c("seriali","SaltChk","SalHowC","SltSHow", "Na_mmol", "Na_mmol_Corrected" ,"Na_mmol_24h_4_10CLAIM", "Na_mmol_24h_4_10CLAIM_Corrected" ,"vegetarn")]
medsset4z <- sav4br[,c("seriali", "bpmedc","bpmedd","diur","beta","aceinh", "calciumb","obpdrug")]
hypset4z <- sav4br[,c("seriali", "hyper140", "hibp140", "hyper1", "highbp1")]
incset4z <- sav4br[,c("seriali","eqvinc","nssec8","hhinc","gor","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","EducFin")]
measset4z <- sav4br[,c("seriali","htval","wtval","bmival")]
ageset4z <- sav4br[,c("seriali","age")]
```

```{r 4setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr1-4a_indiv_uk 
#subsets of the table to identify grouped information
bpset6z <- sav6br[,c("seriali","omsysval","omdiaval")]
#ethnset6 <- sav6br[,c("seriali","ethgr2")]
saltset6z <- sav6br[,c("seriali","SaltChk","SalHowC","SltSHow", "Na_mmol", "Na_mmol_Corrected" ,"Na_mmol_24h_4_10CLAIM", "Na_mmol_24h_4_10CLAIM_Corrected" ,"vegetarn")]
#medsset6 <- sav6br[,c("seriali", "bpmedc","bpmedd","diur","beta","aceinh", "calciumb","obpdrug")]
#hypset6 <- sav6br[,c("seriali", "hyper140", "hibp140", "hyper1", "highbp1")]
incset6z <- sav6br[,c("seriali","eqvinc","nssec8","hhinc","gor","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","EducFin")]
measset6z <- sav6br[,c("seriali","htval","wtval","bmival")]
ageset6z <- sav6br[,c("seriali","age")]
```


```{r 4setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr1-4a_indiv_uk 
#subsets of the table to identify grouped information
bpset8z <- sav8br[,c("seriali","omsysval","omdiaval")]
#ethnset6 <- sav6br[,c("seriali","ethgr2")]
saltset8z <- sav8br[,c("seriali","SaltChk","SalHowC","SltSHow", "Na_mmol", "Na_mmol_Corrected" ,"Na_mmol_24h_4_10CLAIM", "Na_mmol_24h_4_10CLAIM_Corrected" ,"vegetarn")]
#medsset6 <- sav6br[,c("seriali", "bpmedc","bpmedd","diur","beta","aceinh", "calciumb","obpdrug")]
#hypset6 <- sav6br[,c("seriali", "hyper140", "hibp140", "hyper1", "highbp1")]
#incset8 <- sav8br[,c("seriali","eqvinc","nssec8","hhinc","gor","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","EducFin")]
measset8z <- sav8br[,c("seriali","htval","wtval","bmival")]
ageset8z <- sav8br[,c("seriali","age")]
```


```{r 11setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr9-11a_indiv_uk 
#subsets of the table to identify grouped information
bpset11z <- sav11br[,c("seriali","omsysval","omdiaval")]
ethnset11z <- sav11br[,c("seriali" ,"ethgrp5","ethgrp2")]
saltset11z <- sav11br[,c("seriali","SaltChk","SalHowC","SltSHow" , "vegetarn")]
medsset11z <- sav11br[,c("seriali", "bpmedc2","bpmedd2", "diur2","beta2","aceinh2", "calciumb2","obpdrug2","PregNowB")]
hypset11z <- sav11br[,c("seriali", "hyper140_2", "hibp140_2", "hyper1_2", "highbp1_2")]
incset11z <- sav11br[,c("seriali","nssec8","GOR","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","educfinh")]
measset11z <- sav11br[,c("seriali","htval2","wtval2","bmival2","bmivg5")]
ageset11z <- sav11br[,c("seriali","agegad1", "agegad2", "agegch1","agegr1","AgeR")]
```



```{r}
bpset4z[, "omsysval" := as.numeric(omsysval)]
bpset6z[, "omsysval" := as.numeric(omsysval)]
bpset8z[, "omsysval" := as.numeric(omsysval)]
bpset11z[, "omsysval" := as.numeric(omsysval)]

bpset4z[, "omdiaval" := as.numeric(omdiaval)]
bpset6z[, "omdiaval" := as.numeric(omdiaval)]
bpset8z[, "omdiaval" := as.numeric(omdiaval)]
bpset11z[, "omdiaval" := as.numeric(omdiaval)]


bpset4z[, "seriali" := as.numeric(seriali)]
bpset6z[, "seriali" := as.numeric(seriali)]
bpset8z[, "seriali" := as.numeric(seriali)]
bpset11z[, "seriali" := as.numeric(seriali)]



```


```{r}
bpset4z <- data.table(bpset4z)
bpset6z <-data.table(bpset6z)
bpset8z <- data.table(bpset8z)
bpset11z <-data.table(bpset11z)


bpset4z 
bpset6z 
bpset8z
bpset11z

bpsetall <- rbindlist(list(bpset4z,bpset6z,bpset8z,bpset11z))

setkey(bpsetall, seriali)

bpsetall <- bpsetall[NOVA_ForDavid, on = "seriali"]
bpsetall

bpsetall <- earlyrp[bpsetall, on = "seriali"] 

```


```{r}
summary(bpsetall)

Adult_bpsetall <- bpsetall[Age > 18]
summary(Adult_bpsetall)
hist(Adult_bpsetall$Age)
hist(Adult_bpsetall$NOVA_Epct_opti_4)
hist(Adult_bpsetall$NOVA_Gpct_opti_4)
hist(Adult_bpsetall$Sodiummg)


boxplot(Adult_bpsetall$NOVA_Epct_opti_4~
          Adult_bpsetall$SurveyYear)
boxplot(Adult_bpsetall$Sodiummg~
          Adult_bpsetall$SurveyYear)
boxplot(Adult_bpsetall$NOVA_Epct_opti_4~
          Adult_bpsetall$Sex)
plot(Adult_bpsetall$omsysval,Adult_bpsetall$NOVA_Epct_opti_4)
plot(Adult_bpsetall$omsysval,Adult_bpsetall$NOVA_Gpct_opti_4)
plot(Adult_bpsetall$omsysval,Adult_bpsetall$Sodiummg)
```



```{r}
lm1 <-lm(omsysval ~ NOVA_Epct_opti_4+ Age +Sex   , Adult_bpsetall)
lm1
AIC(lm1)
anova(lm1)
plot(lm1)

lm2 <- lm(omsysval~ NOVA_Gpct_opti_4+ Age +Sex , Adult_bpsetall)
lm2
AIC(lm2)
anova(lm2)
lm3 <- lm(omsysval~ Sodiummg+ Age +Sex , Adult_bpsetall)
lm3
AIC(lm3)
anova(lm3)
```