---
title: "litrev"
output:
  html_document:
    df_print: paged
---

```{r libraries ,echo=FALSE}
library(quanteda)
library(quanteda.textstats)
library(quanteda.textmodels)
library(quanteda.textplots)
library(tidyverse)
library(bibtex)
library(readtext)
library(RefManageR)
library(bib2df)
library(ggplot2)
```

```{r read doc, echo=FALSE}
# read document
dat_search1 <- readtext("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/altquant/writlit/search/Primo_BibTeX_Export*.bib")
Prim_search1b <- ReadBib("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/altquant/writlit/search/Primo_BibTeX_Export.bib")
Prim_search2b <- ReadBib("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/altquant/writlit/search/Primo_BibTeX_Export2.bib")
#/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp
scop_search2b <- ReadBib("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/scopus.bib")
scop_searchx <- bib2df("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/scopus.bib")
medl_search2b <- ReadBib("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/medline116.bib")
medl_searchy <- bib2df("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/medline116.bib")
combined_search2b <- scop_search2b + medl_search2b
WriteBib(combined_search2b,file = "combined.bib")

view(medl_searchy)

combined136_search <- bib2df("combined136.bib")

ggplot(combined136_search, aes(x=reorder(CATEGORY, CATEGORY, function(x)-length(x))))+
  geom_bar(fill='red')+  labs(x='Type')

ggplot(combined136_search , aes(x=(as.factor(YEAR)), y=CATEGORY) )+
 geom_boxplot(fill='red')+  labs(x='year')

dat_search1b[author = "Myrie"]
dat_search3 <- dat_search1b + dat_search2b
dat_search3[author = "Myrie"]
combined_search2b[author = "*"]
```

```{r create corpus, echo=FALSE}

cor_dat_search1<- corpus(dat_search1)

summary(cor_dat_search1)

#reshape to paragraphs

#cor_dat_tea <- corpus_reshape(cor_dat_tea, to = "paragraphs")
#summary(cor_dat_tea)

# segment by pattern time stamp
cot_search_seg <- corpus_segment(cor_dat_search1, pattern = "@article{", valuetype = "glob")

summarycot <-summary(cot_search_seg)

#cbind(docvars(cot_tea_seg), text = as.character(cot_tea_seg))
hist(summarycot$Tokens)
hist(summarycot$Sentences)
hist(summarycot$Types)

# tokens of segmented version
tok_search1 <- tokens(cot_search_seg, remove_punct = TRUE, remove_symbols = TRUE, remove_numbers = TRUE)
tok_search2 <- tokens(cot_search_seg, remove_punct = FALSE, remove_symbols = FALSE, remove_numbers = TRUE)
#tok_seg_tea <- tokens_remove(tok_seg_tea, nameanon)

# change to DFM
search1_dfm <-dfm(tok_search1)
#tea_segtok_dfm <- dfm_remove(tea_segtok_dfm, stopwords("en"))
#view(tea_segtok_dfm)

dat_search1b.bib["boot"]





#tea_tok_dfm <-dfm(tokens_remove(toknop_dat_tea, pattern = c(  nameanon )))
search1_dfm <-dfm(tokens_remove(tok_search1, pattern = c( stopwords("en") )))

view(search1_dfm)
plot(topfeatures(search1_dfm, n = 20))
topfeatures(search1_dfm, n = 20)
#plot(topfeatures(tea2_tok_dfm, n = 20))
#topfeatures(tea2_tok_dfm, n = 20)
```

```{r tea, echo=FALSE}
authorsearkwic <- kwic( tok_search1, "author", window = 12)
#teakwic <- kwic(tok_dat_tea,"tea", window = 12)
(authorsearkwic$post)
#segteakwic$docname
#teakwic$docname
typesearkwic <- kwic( tok_search2, "@", window = 8)
#teakwic <- kwic(tok_dat_tea,"tea", window = 12)
(typesearkwic$post)
```

```{r myour, echo=FALSE}
placekwic <- kwic( tok_search1, "place", window = 12)
#oursegteakwic$docname
(placekwic$post)

datekwic <- kwic( tok_search1, "date", window = 12)
#oursegteakwic$docname
datekwic$post
```

```{r wordclouds, echo=FALSE}

set.seed(132)
textplot_wordcloud(search1_dfm, max_words = 100)


#set.seed(132)
#allwordsg <- textplot_wordcloud(tea_tok_dfm, max_words = 100)

#head(rowSums(tea_segtok_dfm), 10)

```
