---
title: "upf salt content"
author: "doh"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
    keep_tex: yes
  html_document:
    toc: yes
    fig_caption: yes
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Nutrient database proportions of foods which are UPF (NOVA 4)

This script will use UPFNOVA to identify foods within the database which are UPF. 
Comparison can then be made between 2008 and 2019.


```{r cars}
library(data.table)
library(readxl)
library(haven)
library(dplyr)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
UPFNOVA <- data.table(read_excel("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/altquant/altquant/UPFNOVA.xlsx"))
#ndns_yr1_nutrientdatabank <- data.table(read_sav("UKDA-6533-spss/spss/spss25/ndns_yr1_nutrientdatabank.sav"))

#ndns_yr11_nutrient <- data.table(read_sav("UKDA-6533-spss/spss/spss25/ndns_yr11_nutrientdatabank_2021-03-19.sav"))

 ndns1_4a_foodleveldietarydata_uk_v2 <- data.table(read_sav("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr1-4a_foodleveldietarydata_uk_v2.sav"))

 ndns_rp_yr9a_foodleveldietarydata_uk_20210831 <- data.table(read_sav("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr9a_foodleveldietarydata_uk_20210831.sav"))
 ndns_rp_yr10a_foodleveldietarydata_uk_20210831 <- data.table(read_sav("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr10a_foodleveldietarydata_uk_20210831.sav"))
 ndns_rp_yr11a_foodleveldietarydata_uk_20210831 <- data.table(read_sav("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_rp_yr11a_foodleveldietarydata_uk_20210831.sav") )
```




```{r}
 UPFNOVA

#labels = c("unprocessed","ingredients","processed","ultraprocessed","complex","supplements")
UPFNOVA[,`Nova group`:= factor(`Nova group`,levels = 1:4)]
UPFNOVA$FoodGroupCode <- UPFNOVA$`food group number`
UPFNOVA[key(FoodGroupCode)]
#plot(UPFNOVA$`Nova group`)

```

###  Does Nova group predict the salt content? 

first in year 1 2008

```{r}

#taking data from diet diary
#specifically coded food gorups

ndns_yr1_nutrientdatabank <- read_sav("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_yr1_nutrientdatabank.sav")
setDT(ndns_yr1_nutrientdatabank)
setkey(ndns_yr1_nutrientdatabank,"FoodGroupCode")
#combine with key for Nova Group

ndns_yr1_nutrientdatabank <- ndns_yr1_nutrientdatabank[UPFNOVA, on= "FoodGroupCode"]
#summarise(ndns_yr1_nutrientdatabank$`NA`)

nasubset <- ndns_yr1_nutrientdatabank[,c("FoodNumber","FoodGroupCode", "FoodName","Nova group","NA","VITD")]
nasubset$Sodium <- list(nasubset$`NA`)

plot(nasubset$`Nova group`)
plot(nasubset$`Nova group`,nasubset$Sodium)
plot(nasubset$`Nova group`, nasubset$VITD)
lmna <- lm(Sodium ~ `Nova group`, nasubset)
lmna
```


then in year 11 2019

```{r}
#taking data from diet diary
#specifically coded food gorups

ndns_yr11_nutrientdatabank <- read_sav("/media/david/Elements1/contents/DOHmed/MPH/MPHModules/dissertation/alternativequant/upfnabp/data/UKDA-6533-spss/spss/spss25/ndns_yr11_nutrientdatabank_2021-03-19.sav")
setDT(ndns_yr11_nutrientdatabank)
setkey(ndns_yr11_nutrientdatabank,"FoodGroupCode")
#combine with key for Nova Group

ndns_yr11_nutrientdatabank <- ndns_yr11_nutrientdatabank[UPFNOVA, on= "FoodGroupCode"]
#summarise(ndns_yr9_nutrientdatabank$`NA`)

nasubset <- ndns_yr11_nutrientdatabank[,c("FoodNumber","FoodGroupCode", "FoodName","Nova group","NA","VITD")]
nasubset$Sodium <- list(nasubset$`NA`)

plot(nasubset$`Nova group`)

lmna <- lm(Sodium ~ `Nova group`, nasubset)
lmna
plot(nasubset$`Nova group`,nasubset$Sodium)
plot(nasubset$`Nova group`, nasubset$VITD)
```

Nova group 4 still is much more likely to contain sodium.


