---
title: "weighting sample"
author: "doh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## weighting ndns

This doc intends to develop a weighted sample for analysis

```{r individual data}
library(haven)
library(survey)
library(data.table)

#Individual data

ndns_rp_yr1_4a_indiv_uk <- read_sav("data/UKDA-6533-spss/spss/spss25/ndns_rp_yr1-4a_indiv_uk.sav")

ndns_rp_yr5_6a_indiv <- read_sav("data/UKDA-6533-spss/spss/spss25/ndns_rp_yr5-6a_indiv.sav")

ndns_rp_yr7_8a_indiv <- read_sav("data/UKDA-6533-spss/spss/spss25/ndns_rp_yr7-8a_indiv.sav")

ndns_rp_yr9_11a_indiv <- read_sav("data/UKDA-6533-spss/spss/spss25/ndns_rp_yr9-11a_indiv_20211020.sav")

 #Uniformizing the name

ndns_rp_yr9_11a_indiv$area <- ndns_rp_yr9_11a_indiv$Area
```

## normalising to weighted vals


first the relative weights are calculated
```{r weight, echo=FALSE}
#Doing the weighting correction, as explain in the PDF "6533_ndns_yrs9-11_weights_guide"

n1 = sum(ndns_rp_yr1_4a_indiv_uk$wti_UKY1234)  #Should be 6828

n2 = sum(ndns_rp_yr5_6a_indiv$wti_Y56)         #Should be 2546

n3 = sum(ndns_rp_yr7_8a_indiv$wti_Y78)         #Should be 2723

n4 = sum(ndns_rp_yr9_11a_indiv$wti_Y911)       #Should be 3558

N <- sum(n1, n2, n3, n4) #Should be 15655
```

now the proportion weight for each is calculated

```{r}
ndns_rp_yr1_4a_indiv_uk$wti_UKY1to11 <- ((ndns_rp_yr1_4a_indiv_uk$wti_UKY1234/n1) * N)  * (4/11)

ndns_rp_yr5_6a_indiv$wti_UKY1to11 <- ((ndns_rp_yr5_6a_indiv$wti_Y56/n2) * N) * (2/11)

ndns_rp_yr7_8a_indiv$wti_UKY1to11 <- ((ndns_rp_yr7_8a_indiv$wti_Y78/n3) * N) * (2/11)

ndns_rp_yr9_11a_indiv$wti_UKY1to11 <- ((ndns_rp_yr9_11a_indiv$wti_Y911/n4) * N) * (3/11)

```


```{r 4setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr1-4a_indiv_uk 
#subsets of the table to identify grouped information
bpset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali","Sys", "Dias", "Sys2", "Dias2","omsysval","omdiaval","CutIll")]
ethnset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali", "EthGrG","EthGrU" ,"ethgr5","ethgr2")]
saltset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali","SaltChk","SalHowC","SltSHow", "Na_mmol", "Na_mmol_Corrected" ,"Na_mmol_24h_4_10CLAIM", "Na_mmol_24h_4_10CLAIM_Corrected" ,"vegetarn")]
medsset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali", "bpmedc","bpmedd","diur","beta","aceinh", "calciumb","obpdrug", "PregNowB")]
hypset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali", "hyper140", "hibp140", "hyper1", "highbp1")]
incset4 <-ndns_rp_yr1_4a_indiv_uk[,c("seriali","eqvinc","nssec8","hhinc","gor","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","EducFin")]
measset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali","htval","wtval","bmival")]
ageset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali","agegad1", "agegad2", "agegch1","agegr1","age")]
weightset4 <- ndns_rp_yr1_4a_indiv_uk[,c("seriali","wti_UKY1to11","astrata1","area")]
```


```{r 6setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr1-4a_indiv_uk 
#subsets of the table to identify grouped information
bpset6 <- ndns_rp_yr5_6a_indiv[,c("seriali","Sys", "Dias", "Sys2", "Dias2","omsysval","omdiaval","CutIll")]
ethnset6 <- ndns_rp_yr5_6a_indiv[,c("seriali", "ethgrp5","ethgrp2")]
saltset6 <- ndns_rp_yr5_6a_indiv[,c("seriali","SaltChk","SalHowC","SltSHow", "Na_mmol", "Na_mmol_Corrected" ,"Na_mmol_24h_4_10CLAIM", "Na_mmol_24h_4_10CLAIM_Corrected" ,"vegetarn")]
medsset6 <- ndns_rp_yr5_6a_indiv[,c("seriali", "bpmedc2","bpmedd2", "diur2","beta2","aceinh2", "calciumb2","obpdrug2","PregNowB")]
hypset6 <- ndns_rp_yr5_6a_indiv[,c("seriali", "hyper140_2", "hibp140_2", "hyper1_2", "highbp1_2")]
incset6 <-ndns_rp_yr5_6a_indiv[,c("seriali","nssec8","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","educfinh")]
measset6 <- ndns_rp_yr5_6a_indiv[,c("seriali","htval","wtval","bmival")]
ageset6 <- ndns_rp_yr5_6a_indiv[,c("seriali","agegad1", "agegad2", "agegch1","agegr1","age")]
weightset6 <- ndns_rp_yr5_6a_indiv[,c("seriali","wti_UKY1to11","astrata1","area")]
```


```{r 8setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr1-4a_indiv_uk 
#subsets of the table to identify grouped information
bpset8 <- ndns_rp_yr5_6a_indiv[,c("seriali","Sys", "Dias", "Sys2", "Dias2","omsysval","omdiaval","CutIll")]
ethnset8 <- ndns_rp_yr5_6a_indiv[,c("seriali", "ethgrp5","ethgrp2")]
saltset8 <- ndns_rp_yr5_6a_indiv[,c("seriali","SaltChk","SalHowC","SltSHow", "Na_mmol", "Na_mmol_Corrected" ,"Na_mmol_24h_4_10CLAIM", "Na_mmol_24h_4_10CLAIM_Corrected" ,"vegetarn")]
medsset8 <- ndns_rp_yr5_6a_indiv[,c("seriali", "bpmedc2","bpmedd2", "diur2","beta2","aceinh2", "calciumb2","obpdrug2","PregNowB")]
hypset8 <- ndns_rp_yr5_6a_indiv[,c("seriali", "hyper140_2", "hibp140_2", "hyper1_2", "highbp1_2")]
incset8 <-ndns_rp_yr5_6a_indiv[,c("seriali","nssec8","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","educfinh")]
measset8 <- ndns_rp_yr5_6a_indiv[,c("seriali","htval","wtval","bmival")]
ageset8 <- ndns_rp_yr5_6a_indiv[,c("seriali","agegad1", "agegad2", "agegch1","agegr1","age")]
weightset8 <- ndns_rp_yr5_6a_indiv[,c("seriali","wti_UKY1to11","astrata1","area")]
```

```{r 11setup variables, message=FALSE, warning=FALSE, include=FALSE}
 #measured and recorded data yr9-11a_indiv_uk 
#subsets of the table to identify grouped information
bpset11 <- ndns_rp_yr9_11a_indiv[,c("seriali","omsysval","omdiaval")]
ethnset11 <- ndns_rp_yr9_11a_indiv[,c("seriali" ,"ethgrp5","ethgrp2")]
saltset11 <- ndns_rp_yr9_11a_indiv[,c("seriali","SaltChk","SalHowC","SltSHow" , "vegetarn")]
medsset11 <- ndns_rp_yr9_11a_indiv[,c("seriali", "bpmedc2","bpmedd2", "diur2","beta2","aceinh2", "calciumb2","obpdrug2","PregNowB")]
hypset11 <- ndns_rp_yr9_11a_indiv[,c("seriali", "hyper140_2", "hibp140_2", "hyper1_2", "highbp1_2")]
incset11 <- ndns_rp_yr9_11a_indiv[,c("seriali","nssec8","GOR","region", "EIMD_2007_quintile","EIMD_2010_quintile","EIMD_2015_quintile","educfinh")]
measset11 <- ndns_rp_yr9_11a_indiv[,c("seriali","htval2","wtval2","bmival2","bmivg5")]
ageset11 <- ndns_rp_yr9_11a_indiv[,c("seriali","agegad1", "agegad2", "agegch1","agegr1")]
weightset11 <- ndns_rp_yr9_11a_indiv[,c("seriali","wti_UKY1to11","astrata1","area")]
```

```{r}

dw <- svydesign(ids = ~area, weights = ~ wti_UKY1to11, strata=~astrata1, data = ndns_rp_yr1_4a_indiv_uk)

svymean(ndns_rp_yr1_4a_indiv_uk$Energykcal, dw)
```








