---
title: "zcnova"
author: "doh"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
    keep_md: yes
  word_document: 
    toc: yes
    fig_caption: yes
    keep_md: yes
  pdf_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
    keep_tex: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ZC nova



```{r load data, echo=FALSE}
library(readxl)
library(data.table)
NOVA_ForDavid <- as.data.table(read_excel("data/NOVA_ForDavid.xlsx"))

NOVA_ForDavid[, Sex := factor(Sex, levels = 1:2)]
NOVA_ForDavid[, Country := factor(Country)]
NOVA_ForDavid[, Country := factor(SurveyYear)]


summary(NOVA_ForDavid)

Adult_NOVA_ForDavid <- NOVA_ForDavid[Age > 18]
summary(Adult_NOVA_ForDavid)
hist(Adult_NOVA_ForDavid$Age)
hist(Adult_NOVA_ForDavid$NOVA_Epct_opti_4)
hist(Adult_NOVA_ForDavid$NOVA_Gpct_opti_4)


boxplot(Adult_NOVA_ForDavid$NOVA_Epct_opti_4~
          Adult_NOVA_ForDavid$SurveyYear)
boxplot(Adult_NOVA_ForDavid$NOVA_Epct_opti_4~
          Adult_NOVA_ForDavid$Sex)
```

## regression



```{r regression, echo=FALSE}
lm( Adult_NOVA_ForDavid$NOVA_Epct_opti_4~ Age +Sex + Country +SurveyYear, Adult_NOVA_ForDavid)
AIC

lm( Adult_NOVA_ForDavid$NOVA_Gpct_opti_4~ Age +Sex + Country+SurveyYear, Adult_NOVA_ForDavid)
AIC

```


